# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67bb2edd0a38256d47e177dc2b2e1d213c756f174d5b50f235549ad63c36136981b60900ae33722f21a3a4bb7ca43b7ffd92f7e6c2484a09ac2c5d8758ae7aea

test:
  secret_key_base: a69c914c0253dc836f7aea67a1cc83893cee6fb7970f562b92977fb53dfb00435c97b8ecf6e6af020d68e800d5cf402ae2666cd9360b97a635863ca48df4c85a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
